{
	"version": 1658681651,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/btn_jogar-sheet0.png",
		"images/igual-sheet0.png",
		"images/mais-sheet0.png",
		"images/n-sheet0.png",
		"images/n2-sheet0.png",
		"images/n3-sheet0.png",
		"images/telainicial-sheet0.png",
		"images/x-sheet0.png",
		"images/btn_home-sheet0.png",
		"images/btn_reiniciar-sheet0.png",
		"images/telafimdejogo-sheet0.png",
		"images/comsom-sheet0.png",
		"images/comsom-sheet1.png",
		"images/erro-sheet0.png",
		"images/acerto-sheet0.png",
		"images/teladojogov-sheet0.png",
		"media/hurt.m4a",
		"media/hurt.ogg",
		"media/bensound-jazzyfrenchy (online-audio-converter.com).m4a",
		"media/bensound-jazzyfrenchy (online-audio-converter.com).ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}